# website settings
website:
  title: "Osmary A. Medina-Báez"                                # Osmary Medina-Báez
  description: "Postdoctoral research associate and NSF Postdoctoral Research Fellow at University of Tennessee, Knoxville."   # Ecologist. Ecophysiologist. Herpetologist. 
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Research projects"
        href: projects/index.qmd
      - text: "Recent conferences"
        href: conferences/index.qmd
      - text: "Mentoring"
        href: mentoring/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/osmary-medina/
      - icon: bluesky
        href: https://bsky.app/profile/osmarymedina.bsky.social
      - icon: envelope
        aria-label: email
        href: mailto:osmary.medina2@gmail.com 
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Osmary Medina-Báez </span>
 
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true