---
title: Publications
---

Fair, H., Medina-Báez, O.A., Spiecker, B.J., Gan, Q., Cheung, Y.Y., D'Bastiani, E., & Goldsmith, G. R. 2024. Can AI interpretation increase inclusivity?. Frontiers in Ecology and the Environment, 22(10). 

Diamond, S.E., da Silva, C.R., & Medina-Báez, O.A. 2024. A multicontinental dataset of butterfly thermal physiological traits. Scientific data, 11(1), 1348.

Medina-Báez, O.A., Lenard, A., Muzychuk, R.A., da Silva, C.R. and Diamond, S.E., 2023. Life cycle complexity and body mass drive erratic changes in climate vulnerability across ontogeny in a seasonally migrating butterfly. Conservation Physiology, 11(1), p.coad058.

Prileson, E.G., Clark, J., Diamond, S.E., Lenard, A., Medina-Báez, O.A., Yilmaz, A.R. and Martin, R.A., 2023. Keep your cool: Overwintering physiology in response to urbanization in the acorn ant, Temnothorax curvispinosus. Journal of Thermal Biology, 114, p.103591.

Veselka, A.J., Aponte‐Gutiérrez, A., Medina‐Báez, O.A. and Watling, J.I., 2023. Upper thermal limits predict herpetofaunal responses to forest edge and cover. Biotropica, 55(2), pp.540-550.


```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="btn btn-primary" href="https://scholar.google.com/citations?user=591aLD4AAAAJ&hl=en&oi=ao" role="button" target="_blank" style="padding: 15px 30px;">View my google scholar page</a>
</div>
```
